openapi: 3.0.0
info:
  title: Dexa recruitment bot jobs board api
  description: This is the Api designed to manage Dexa recruitment bot jobs.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/kibico/DexaJobs/1.0.0
  description: SwaggerHub API Auto Mocking
security:
- application:
  - read
  - write
  - delete
  - update
  - admin
paths:
  /users:
    get:
      tags:
      - users
      summary: list all users
      responses:
        "200":
          description: OK
    post:
      tags:
      - users
      summary: add a new user
      responses:
        "200":
          description: OK
  /users/{userId}:
    put:
      tags:
      - user
      summary: update a user's profile
      parameters:
      - name: userId
        in: path
        description: A user unique identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    delete:
      tags:
      - user
      summary: delete a user
      parameters:
      - name: userId
        in: path
        description: A user unique identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
  /jobs:
    get:
      tags:
      - jobs
      summary: List available jobs
      responses:
        "200":
          description: OK
    post:
      tags:
      - jobs
      summary: submit a new job
      responses:
        "200":
          description: OK
  /jobs/{jobId}:
    put:
      tags:
      - jobs
      summary: update a job details
      parameters:
      - name: jobId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    delete:
      tags:
      - jobs
      summary: delete a job
      parameters:
      - name: jobId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
  /jobs/{jobId}/steps:
    get:
      tags:
      - jobs steps
      summary: list a job steps
      parameters:
      - name: jobId
        in: path
        description: targeted job unique identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    post:
      tags:
      - jobs steps
      summary: add a new step to a job
      parameters:
      - name: jobId
        in: path
        description: targeted job unique identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
  /jobs/{jobId}/steps/{stepId}:
    put:
      tags:
      - jobs steps
      summary: update a job step
      parameters:
      - name: jobId
        in: path
        description: targeted job unique identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: stepId
        in: path
        description: target job application step's unique identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    delete:
      tags:
      - jobs steps
      summary: delete a job step
      parameters:
      - name: jobId
        in: path
        description: targeted job unique identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: stepId
        in: path
        description: target job application step's unique identifier
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
  /applications:
    get:
      tags:
      - applications
      summary: List available applications
      description: "This operation shows how to override the global security defined\
        \ above, as we want to open it up for all users."
      responses:
        "200":
          description: OK
      security: []
components:
  schemas:
    Job:
      type: object
      properties:
        id:
          type: integer
          format: int64
    User:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    OkResponse:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
          format: int32
          default: 0
        message:
          type: string
          default: OK
        data:
          type: object
  parameters:
    jobId:
      name: jobId
      in: path
      description: targeted job unique identifier
      required: true
      style: simple
      explode: false
      schema:
        type: string
    stepId:
      name: stepId
      in: path
      description: target job application step's unique identifier
      required: true
      style: simple
      explode: false
      schema:
        type: string
    userId:
      name: userId
      in: path
      description: A user unique identifier
      required: true
      style: simple
      explode: false
      schema:
        type: string
  securitySchemes:
    application:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: http://example.com/oauth/token
          scopes:
            write: allows modifying resources
            read: allows reading resources
